import React from "react";
import "./Seo.css";

const AboutSEO = () => {
  return (
    <div className="">
      <section className="tech-about-seo">
        <div className="row">
          <div className="col-lg-7 col-12 order-2 order-lg-1">
            <div className="about-seo-bg">
              <img src="assets/img/about-seo.png" alt="SEO" className=""/>
            </div>
          </div>
          <div className="col-lg-5 col-12 order-2 order-lg-2">
            <div className="Seo-responsive">
              <h1>
                What is <span>SEO?</span>
              </h1>
              <p>
                SEO is a kind of service through which you can get success for
                online business. The traffic potential is generated by SEO for
                all types of websites. SEO is a format of Search engine
                optimization. Through it, you can optimize your website & can
                achieve higher rankings in search engines with organic results.
              </p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default AboutSEO;
